service: finniu-integrations

frameworkVersion: "3"

custom:
  wsgi:
    app: src.app.app
  pythonRequirements:
    dockerizePip: true

  dotenv:
    basePath: ./
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage}
  region: ${env:REGION}
  memorySize: 512
  timeout: 30

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin
package:
  exclude:
    - "node_modules/**"
    - "*.md"
    - "package-lock.json"
  include:
    - "src/**"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"
    layers:
      - arn:aws:lambda:${env:WKHTMLPDF_LAYER_ARN}
