service: finniu-integrations

frameworkVersion: '3'

custom:
  wsgi:
    app: src.app.app
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true
    slim: false

  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: us-east-2
  memorySize: 128
  timeout: 15
  #   REGION: ${env:REGION}
  
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:us-east-2:347599033421:layer:wkhtmltopdf-0_12_6:1
  rateHandler:
    handler: cron.run
    events:
      - schedule: rate(1 minute)
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin
package:
  exclude:
    - "node_modules/**"
    - "*.md"
    - "package-lock.json"
  include:
    - "src/**"